name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to Server
        run: |
          # SSH into your server and do the following:
          ssh -o StrictHostKeyChecking=no vcm@vcm-45219.vm.duke.edu << 'EOF'
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
            export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
            echo "NVM has been loaded."
            nvm install node
            cd /var/www/notes-web-app
            git config --global --add safe.directory /var/www/notes-web-app
            sudo git reset --hard HEAD
            sudo git pull origin main

            cd server
            source venv/bin/activate
            pip3 install django gunicorn
            cd notes
            python3 manage.py migrate

            cd ../../client
            npm install
            npm run build

            sudo systemctl restart gunicorn
          EOF