name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to Server
        run: |
          # SSH into your server and do the following:
          ssh -o StrictHostKeyChecking=no vcm@vcm-45219.vm.duke.edu << 'EOF'
            cd /var/www/notes-web-app
            git pull origin main

            cd server
            source venv/bin/activate
            pip3 install django gunicorn
            python3 manage.py migrate

            cd ../client
            npm install
            npm run build

            sudo systemctl restart gunicorn
          EOF